[package]
name = "dynamics_example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]


[dependencies]
system_solver = { path = "../.." }
struct_to_array = { workspace = true }
field_names_and_counts = { workspace = true }


[dev-dependencies]
test-case = "3.3.1"
